### PR TITLE
Add support for new commands

### PR DESCRIPTION
**Pull request by oblogic7**
Creating this PR to get these changes back into the main project.

### CODE REVIEW

**Comment by thingyt** [comment]
I paused and didn't commit because I wasn't sure the method I used would actually work. I was trying to figure out a test environment so I could try it, but got side tracked. 
Instead of the lines: 
cmd = 'CC ' + "1:1";
 which works but i think is using the ross switcher bank commands which as far as I can tell only works for play and stop. 
   "Ross Video Switchers
    bank 1 control 1 – Play Command
    bank 1 control 2 – Pause Command" 
- from https://livingasone.com/documentation/decoding/#RossTalk

Instead if we use 'CC play', 'CC FTB' etc I think we can use the additional commands as listed: 
    "ProPresenter Via “Custom Controls”
    “CC play” – Play Command
    “CC pause” – Pause Command
    “CC PAFFB” – Play And Fade From Black
    “CC FTBAP” – Fade To Black And Pause
    “CC FFB” – Fade From Black (no change to playing state)
    “CC FTB” – Fade To Black (no change to playing state)"
- from https://livingasone.com/documentation/decoding/#RossTalk

Unfortunately I don't have a great test environment setup to compile and test code right now. The piece I was uncertain about is whether the 1:1 is a text bank command or referencing the option list which would pull in the names and create the file. 

I only realized my untested code was getting pulled in today after I deleted my fork thinking someone else had added the extra commands and I didn't need to follow up on testing.

**Comment by JeffreyDavidsz** [comment]
@obblogic7Looking at the pull request and description it seems it's tested. Please make sure when a pull request is made, the code is tested.
@thingyt Thanks for the suggestion for the commands. I'll change them later and then you can pick a build.

**Comment by JeffreyDavidsz** [comment]
Changed the commands, please test with the correct build

**Comment by oblogic7** [comment]
Where can I find a build with these changes? I'll be glad to verify them.

**Comment by JeffreyDavidsz** [comment]
User arrea under 1.4 click on builds (on the website)

**Pull request merged**
